### ISSUE TITLE
Does not sync selected repos with the "Sync selected" button.

### ISSUE THREAD

**Issue by Priyansh2** [alexivkin/forkrefresh#1]
I had to manually sync the repos one by one with the button appeared on the right most side but instead want to do it all at once. Your "Sync selected" button is not able to do that. Please fix that. Also I am not able to understand why it cannot sync the certain repos as in attached screenshot. It shows a "!" mark on them. 
![forkrefresh 9-8-2018 5-24-13 pm](https://user-images.githubusercontent.com/13703438/45253907-14c44300-b38c-11e8-9538-57ed4842b979.png)
![forkrefresh 9-8-2018 5-25-23 pm](https://user-images.githubusercontent.com/13703438/45253915-3291a800-b38c-11e8-82fe-adca5d71ddcc.png)

**Comment by alexivkin** [comment]
Sync selected looks like a bug, I'll fix it when I have time. The exclamation button gives you a chance to review the changes before syncing. Click on it and select "see changes" - if there are no changes or if they are unimportant you can then click "discard changes" and your fork will be forcefully syncrhonized.
