### ISSUE TITLE
Keeping Organization forks up to date isn't supported

### ISSUE THREAD

**Issue by jlc-christie** [alexivkin/forkrefresh#2]
Works perfectly on personal repo's, but a research team I'm working with have created an organization page to store any tools that are created there, however they want them to be forked in and kept up to date rather than actually transferring the repository over to the organization, so I was hoping I could use this. 

OAuth asked me to authenticate for the organization as well as my personal account so the application should have access to them but they're not listed? 

Would be great if this was supported.

**Comment by jayvdb** [comment]
This would be especially useful because the web interface would be ideal to allow 'managers' to easily see when there are upstream changes available to those forks.

**Comment by alexivkin** [comment]
Not sure I understand the use case. Does the org store repos forked from somewhere else and the org account would be refreshing/viewing the state of the forks against the originals? Just like it is now for personal accounts?
